#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/lou/.Xmodmap"

#set wallpaper to last used
fbsetbg -l

#transparent term over the wallpaper 
aterm -tr +sb -fg black -bg white &
#quake style term with shading
urxvt -name kuake -tr +sb -sh 60 -fg white -bg black -pe 'kuake<0xff67>' &

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/lou/.fluxbox/log"
